POST http://localhost:3000/
Content-Type: application/json

{
    "equipmentImage": "test",
    "name" : "test",
    "description": "test",
    "tutorial": "test",
    "videoTutorialLink": "test",
    "targetMuscles": ["test", "test2"]
}
###
GET http://localhost:3000/1

###
PUT http://localhost:3000/3
Content-Type: application/json

{
    "equipmentImage": "test",
    "name" : "asiufaif",
    "description": "asdad",
    "tutorial": "dsjoiaf",
    "videoTutorialLink": "ashfoia",
    "targetMuscles": ["test", "test2"]
}

###
DELETE http://localhost:3000/4
